build: Remove final reference to $TEST_FUNCTIONS
We had already removed $TEST_FUNCTIONS in virt-v2v tests, but it was
still referenced in a few places in the common submodule.  These
references in common/ have now gone so we can remove the final
remnants:

  commit 8137d47d0e654065391151eb275e3b64f230f6f5
  Author: Richard W.M. Jones <rjones@redhat.com>
  Date:   Thu Feb 13 11:13:55 2025 +0000

    mlcustomize, mltools: Replace $TEST_FUNCTIONS

    TEST_FUNCTIONS is being removed from libguestfs and guestfs-tools (it
    was removed from virt-v2v a while back).  Make the same adjustment in
    the common submodule.

See also this libguestfs commit:
https://github.com/libguestfs/libguestfs/commit/b5fbc7e617584aea8789b36aaa43e84f3ac7806e

A few small additions were also needed to tests/functions.sh.in, for
some missing functions that were needed by the slow tests under
common/mlcustomize.

diff --git a/tests/functions.sh.in b/tests/functions.sh.in
--- a/tests/functions.sh.in
+++ b/tests/functions.sh.in
@@ -150,6 +150,53 @@ skip_if_root ()
 fi
 }
 
+# Skip if the current arch != $1.
+skip_unless_arch ()
+{
+    local m="$(uname -m)"
+    case "$1" in
+        # Some magic happens for some architectures.
+        arm)
+            if [[ ! "$m" =~ ^arm ]]; then
+                echo "$(basename $0): test skipped because the current architecture ($m) is not arm (32 bit)"
+                exit 77
+            fi
+            ;;
+        i?86)
+            if [[ ! "$m" =~ ^i?86 ]]; then
+                echo "$(basename $0): test skipped because the current architecture ($m) is not $1"
+                exit 77
+            fi
+            ;;
+        *)
+            if [ "$m" != "$1" ]; then
+                echo "$(basename $0): test skipped because the current architecture ($m) is not $1"
+                exit 77
+            fi
+            ;;
+    esac
+}
+
+# Skip if $1 is not known to virt-builder.
+skip_unless_virt_builder_guest ()
+{
+    if ! virt-builder -l "$1" >/dev/null 2>&1; then
+        echo "$(basename $0): test skipped because $1 is not known to virt-builder"
+        exit 77
+    fi
+}
+
+# Run an external command and skip if the command fails.  This can be
+# used to test if a command exists.  Normally you should use
+# `cmd --help' or `cmd --version' or similar.
+skip_unless ()
+{
+    if ! "$@"; then
+        echo "$(basename $0): test skipped because $1 is not available"
+        exit 77
+    fi
+}
+
 # Slow tests should always call this function.  (See guestfs-hacking(1)).
 slow_test ()
 {
